### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Tommie1236** [MikeEllis-personal/DMXfire#1]
Can you maybe give me a little example how I can use this? I'm trying to make a tiny dmx controller using a RPI pico and this is the only python software i have found.

**Comment by MikeEllis-T67M** [comment]
Thanks for reaching out to me. The code is very definitely unfinished - please use it as a basis, but it may (or may not!) work correctly. I know, for example, that it will fail with RDM over DMX universes - I haven't worked out how to fix this yet.

As a quick way to see how to use the code, the test harness as the end of dmx.py should be enough to get you going.

Good luck!

Mike.

**Comment by MikeEllis-personal** [comment]
As a quick way to see how to use the code, the test harness as the end of dmx.py should be enough to get you going.

**Comment by Tommie1236** [comment]
Thanks for responding. 
That was what I was looking for.

Another question:
How did you attach/connect your dmx?
To the gpio pins directly, connect one pin to a tll to rs485 converter or something else?

**Comment by MikeEllis-personal** [comment]
At the moment I am connecting a protocol analyser to the GPIO pins, and also using the transmit code to exercise the receive code. I have a half-completed PCB design for the level shifter and opto isolator based on the information at http://www.mathertel.de/Arduino/DMXShield.aspx but as yet I've not built and tested this.

**Comment by bdyetton** [comment]
@Tommie1236 Did you get this working with a rs485 converter in the end?

**Comment by Tommie1236** [comment]
No, I coudn't get it working before I wanted to use it, after that I was working on some other things and completely forgot about it.
And I don't currently have any dmx fixtures to test with.
Sorry

**Comment by MikeEllis-personal** [comment]
I have some a fair bit on the code recently,  and I now have proved that it works for reception of DMX with a commercial RS485 level shifter from eBay. There are still some rough edges to smooth off,  and I haven't yet done real world testing of the transmit side,  however the firelight effect I have created works really well!
